#!/bin/bash
####################################################
# Upload a file to dropbox and output public address

dropbox-api put $1 dropbox:/Public/

DRPBX_UID=`dropbox-api uid`
FILE=`basename $1`

echo "http://dl.dropbox.com/u/$DRPBX_UID/$FILE"
